create table if not exists public.gifts (
    id text primary key,
    category text not null,
    name text not null,
    price integer,
    detail text not null,
    purchase_link text,
    image text,
    sort_order integer not null,
    reserved_by_name text,
    reserved_by_phone text,
    confirmed_at timestamptz
);

alter table public.gifts add column if not exists purchase_link text;
alter table public.gifts add column if not exists image text;

create unique index if not exists gifts_name_key on public.gifts (name);
create index if not exists gifts_sort_order_idx on public.gifts (sort_order);

create table if not exists public.presence_confirmations (
    id bigint generated always as identity primary key,
    guest_name text not null,
    guest_phone text not null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists presence_confirmations_created_at_idx on public.presence_confirmations (created_at desc);

create table if not exists public.pix_confirmations (
    id bigint generated always as identity primary key,
    guest_name text not null,
    guest_phone text not null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists pix_confirmations_created_at_idx on public.pix_confirmations (created_at desc);

delete from public.gifts;

insert into public.gifts (
    id,
    category,
    name,
    price,
    detail,
    purchase_link,
    image,
    sort_order,
    reserved_by_name,
    reserved_by_phone,
    confirmed_at
) values
    (
        '01',
        'Prestige',
        'Jogo de panelas',
        null,
        'Base para cozinhar arroz, feijao, molhos, legumes e refeicoes do dia a dia.',
        'https://www.mercadolivre.com.br/p/MLB32466350?offer_type=BEST_PRICE&pdp_filters=item_id:MLB4053374163&matt_tool=38524122#origin=share&sid=share&wid=MLB4053374163&action=whatsapp',
        'IMGS/produtos/1.jpeg',
        0,
        null,
        null,
        null
    ),
    (
        '8',
        'Prestige',
        'Jogo de pratos',
        null,
        'Conjunto de pratos para o dia a dia e ocasioes especiais.',
        'https://www.mercadolivre.com.br/jogo-6-pratos-rasos-grande-vidro-branco-25cm-restaurante/up/MLBU3503321287?pdp_filters=item_id%3AMLB5832115552&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB5832115552',
        'IMGS/produtos/8.jpeg',
        1,
        null,
        null,
        null
    ),
    (
        '14',
        'Prestige',
        'Liquidificador',
        null,
        'Para vitaminas, sucos, molhos e receitas da casa.',
        'https://www.mercadolivre.com.br/liquidificador-com-15-velocidades-oster-de-1400w-potente/up/MLBU2142765421?pdp_filters=item_id%3AMLB4543427767&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB4543427767',
        'IMGS/produtos/14.jpeg',
        2,
        null,
        null,
        null
    ),
    (
        '16',
        'Prestige',
        'Air fryer',
        null,
        'Para preparar receitas com praticidade no dia a dia.',
        'https://www.mercadolivre.com.br/air-fryer-philco-55l-revestimento-redstone-1500w-paf55b/p/MLB49952088?pdp_filters=item_id%3AMLB4317772143&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB4317772143',
        'IMGS/produtos/16.jpeg',
        3,
        null,
        null,
        null
    ),
    (
        '28',
        'Prestige',
        'Jogo de cama casal',
        null,
        'Conjunto para trazer conforto e completar o quarto.',
        'https://www.mercadolivre.com.br/jogo-de-lencol-casal-padrao-4-pcs-percal-600-fios-egipcio/up/MLBU3547767615?pdp_filters=item_id%3AMLB5920449146&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB5920449146',
        'IMGS/produtos/28.jpeg',
        4,
        null,
        null,
        null
    ),
    (
        '31',
        'Prestige',
        'Cobertor',
        null,
        'Cobertor para deixar as noites mais confortaveis.',
        'https://produto.mercadolivre.com.br/MLB-4040388707?attributes=FABRIC_DESIGN:RnJpbyBJbnRlbnNvIEhvdGVsIFJlY2hlaW8gRHV2ZXQgTWFuZ2EgRXN0YW1wYSBLaXQ=,COLOR_SECONDARY_COLOR:QmVnZQ==&matt_tool=38524122#origin=share&sid=share&action=whatsapp',
        'IMGS/produtos/31.jpeg',
        5,
        null,
        null,
        null
    ),
    (
        '37',
        'Prestige',
        'Varal',
        null,
        'Varal para secagem pratica das roupas no dia a dia.',
        'https://produto.mercadolivre.com.br/MLB-6205251934-varal-de-roupas-parede-resistente-articulado-60-kg-reforcado-_JM?matt_tool=38524122&attributes=COLOR_SECONDARY_COLOR%3AUHJldG8%3D#origin=whatsapp&sid=whatsapp',
        'IMGS/produtos/37.jpeg',
        6,
        null,
        null,
        null
    ),
    (
        '38',
        'Prestige',
        'Ferro de passar roupa',
        null,
        'Ferro a vapor para facilitar o cuidado com as roupas.',
        'https://www.mercadolivre.com.br/ferro-de-passar-roupas-a-vapor-philips-walita-dst5040-serie-5000-1470w-preto/p/MLB24125129?pdp_filters=item_id%3AMLB3546429381&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB3546429381',
        'IMGS/produtos/38.jpeg',
        7,
        null,
        null,
        null
    ),
    (
        '39',
        'Prestige',
        'Tabua de passar roupa',
        null,
        'Base pratica para passar roupas com mais conforto.',
        'https://produto.mercadolivre.com.br/MLB-2963831888-mesa-passadeira-de-passar-roupa-dobravel-extra-forte-grande-_JM?matt_tool=38524122#origin=whatsapp&sid=whatsapp',
        'IMGS/produtos/39.jpeg',
        8,
        null,
        null,
        null
    ),
    (
        '02',
        'Prime',
        'Panela de pressao',
        null,
        'Essencial para feijao, carnes, cozidos e preparo mais rapido.',
        'https://www.mercadolivre.com.br/up/MLBU1987757783?offer_type=BEST_PRICE&pdp_filters=item_id:MLB4966648582&matt_tool=38524122#origin=share&sid=share&wid=MLB4966648582&action=whatsapp',
        'IMGS/produtos/2.jpeg',
        9,
        null,
        null,
        null
    ),

    (
        '7',
        'Prime',
        'Potes hermeticos',
        null,
        'Otimos para manter mantimentos organizados e bem vedados.',
        'https://www.mercadolivre.com.br/kit-10-organizadores-pote-hermetico-empilhavel-em-acrilico-cor-transparente/p/MLB68593211?pdp_filters=item_id%3AMLB4633860471&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB4633860471',
        'IMGS/produtos/7.jpeg',
        10,
        null,
        null,
        null
    ),
    (
        '12',
        'Prime',
        'Garrafa termica',
        null,
        'Ideal para manter cafe e bebidas na temperatura certa.',
        'https://www.mercadolivre.com.br/garrafa-termica-lumina-9751-termolar-1-litro-aco-inox/p/MLB29554584?pdp_filters=item_id%3AMLB5361809522&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB5361809522',
        'IMGS/produtos/12.jpeg',
        11,
        null,
        null,
        null
    ),
    (
        '21',
        'Prime',
        'Conjunto de utensilios de cozinha',
        null,
        'Conjunto pratico para o preparo das refeicoes do dia a dia.',
        'https://www.mercadolivre.com.br/conjunto-utensilios-profissional-10-pecas-cozinha-silicone/up/MLBU1729594100?pdp_filters=item_id%3AMLB5636036574&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB5636036574',
        'IMGS/produtos/21.jpeg',
        12,
        null,
        null,
        null
    ),
    (
        '25',
        'Prime',
        'Chaleira eletrica',
        null,
        'Pratica para aquecer agua com rapidez no dia a dia.',
        'https://www.mercadolivre.com.br/chaleira-eletrica-2l-inox-automatica-aquecimento-rapido/up/MLBU3828948159?pdp_filters=item_id%3AMLB6429240088&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB6429240088',
        'IMGS/produtos/25.jpeg',
        13,
        null,
        null,
        null
    ),
    (
        '29',
        'Prime',
        'Travesseiros',
        null,
        'Par de travesseiros para mais conforto na cama.',
        'https://www.mercadolivre.com.br/kit-c2-travesseiros-luxo-matelado-fibra-antialergica-50x70-branco/p/MLB64904437?pdp_filters=item_id%3AMLB6195001116&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB6195001116',
        'IMGS/produtos/29.jpeg',
        14,
        null,
        null,
        null
    ),
    (
        '32',
        'Prime',
        'Tolha de banho',
        null,
        'Jogo para banho e rosto com uso no dia a dia.',
        'https://produto.mercadolivre.com.br/MLB-5385849760-jogo-kit-4-pecas-tolha-de-banho-rosto-capri-gigante-algodo-_JM?matt_tool=38524122&attributes=COLOR_SECONDARY_COLOR%3AUm9zYSBSb23DoyAvIE9mZiBXaGl0ZQ%3D%3D#origin=whatsapp&sid=whatsapp',
        'IMGS/produtos/32.jpeg',
        15,
        null,
        null,
        null
    ),
    (
        '40',
        'Prime',
        'Mop',
        null,
        'Item para limpeza pratica dos ambientes da casa.',
        'https://www.mercadolivre.com.br/mop-nybc-mop-giratorio-plus-com-balde-centrifuga-cinza/p/MLB50921911?pdp_filters=item_id%3AMLB5031588890&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB5031588890',
        'IMGS/produtos/40.jpeg',
        16,
        null,
        null,
        null
    ),

    (
        '03',
        'Especial',
        'Frigideira antiaderente grande',
        null,
        'Serve para ovos, carnes, legumes, tapioca, panquecas e lanches.',
        'https://www.mercadolivre.com.br/frigideira-funda-antiaderente-24-cm-com-tampa-tramontina-cor-grafite/p/MLB44274771?pdp_filters=item_id%3AMLB4196692767&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB4196692767',
        'IMGS/produtos/3.jpeg',
        17,
        null,
        null,
        null
    ),
    (
        '5',
        'Especial',
        'Potes',
        null,
        'Conjunto versatil para armazenar e organizar alimentos.',
        'https://www.mercadolivre.com.br/kit-4-potes-vidro-1040ml-hermetico-marmita-forno-refratario/up/MLBU3534134664?pdp_filters=item_id%3AMLB4283700061&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB4283700061',
        'IMGS/produtos/5.jpeg',
        18,
        null,
        null,
        null
    ),
    (
        '6',
        'Especial',
        'Travessa de vidro grande',
        null,
        'Travessa ideal para forno, freezer e servir a mesa.',
        'https://www.mercadolivre.com.br/kit-2-travessas-de-vidro-forno-freezer-marinex-pirex-grande/up/MLBU3544504490?pdp_filters=item_id%3AMLB5905336188&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB5905336188',
        'IMGS/produtos/6.jpeg',
        19,
        null,
        null,
        null
    ),
    (
        '13',
        'Especial',
        'Jarra',
        null,
        'Jarra para agua, sucos e outras bebidas.',
        'https://www.mercadolivre.com.br/jarra-de-vidro-tampa-higienica-inox-1-litro-borossilicato/up/MLBU3827967757?pdp_filters=item_id%3AMLB4516227995&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB4516227995',
        'IMGS/produtos/13.jpeg',
        20,
        null,
        null,
        null
    ),
    (
        '15',
        'Especial',
        'Sanduicheira ou grill',
        null,
        'Pratica para lanches, grelhados e refeicoes rapidas.',
        'https://www.mercadolivre.com.br/sanduicheira-e-grill-pgr21pi-maxx-clean-1000w-philco-prateado/p/MLB28017294?pdp_filters=item_id%3AMLB3509498657&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB3509498657',
        'IMGS/produtos/15.jpeg',
        21,
        null,
        null,
        null
    ),
    (
        '22',
        'Especial',
        'Escorredor de arroz/macarrao',
        null,
        'Ajuda no preparo e escorrimento de arroz e macarrao.',
        'https://www.mercadolivre.com.br/kit-escorredor-de-macarrao-24cm--escorredor-arroz-inox-26cm/up/MLBU2220575429?pdp_filters=item_id%3AMLB3175145613&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB3175145613',
        'IMGS/produtos/22.jpeg',
        22,
        null,
        null,
        null
    ),
    (
        '23',
        'Especial',
        'Tigela grande',
        null,
        'Util para servir, misturar e preparar receitas maiores.',
        'https://www.mercadolivre.com.br/conjunto-3-bacias-tigelas-saladeiras-bowl-inox-3-litros/up/MLBU803087994?pdp_filters=item_id%3AMLB4540747558&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB4540747558',
        'IMGS/produtos/23.jpeg',
        23,
        null,
        null,
        null
    ),
    (
        '27',
        'Especial',
        'Porta temperos',
        null,
        'Ajuda a manter os temperos organizados e ao alcance.',
        'https://www.mercadolivre.com.br/porta-temperos-e-condimentos-giratorio-9-potes-vidro-preto-solar/p/MLB66067381?pdp_filters=item_id%3AMLB6362014218&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB6362014218',
        'IMGS/produtos/27.jpeg',
        24,
        null,
        null,
        null
    ),
    (
        '36',
        'Especial',
        'Cesto de roupa suja',
        null,
        'Ajuda a organizar roupas de forma pratica na lavanderia.',
        'https://www.mercadolivre.com.br/cesto-de-roupa-suja-bambu-dobravel-com-tampa-alcas-72-litros/up/MLBU3726935279?pdp_filters=item_id%3AMLB4421996357&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB4421996357',
        'IMGS/produtos/36.jpeg',
        25,
        null,
        null,
        null
    ),

    (
        '04',
        'Essencial',
        'Assadeira retangular',
        null,
        'Para forno: carnes, lasanha, legumes, bolos simples e gratinados.',
        'https://www.mercadolivre.com.br/jogo-de-assadeiras-aluminio-2-pecas-tramontina-bolo-e-pudim/p/MLB27497694?pdp_filters=item_id%3AMLB3659308875&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB3659308875',
        'IMGS/produtos/4.jpeg',
        26,
        null,
        null,
        null
    ),
    (
        '9',
        'Essencial',
        'Jogo de talheres',
        null,
        'Conjunto para servir as refeicoes do dia a dia.',
        'https://www.mercadolivre.com.br/faqueiro-24-pecas-buzios-inox-23799071-tramontina-cor-cinza-claro/p/MLB36638741?pdp_filters=item_id%3AMLB5214565886&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB5214565886',
        'IMGS/produtos/9.jpeg',
        27,
        null,
        null,
        null
    ),
    (
        '10',
        'Essencial',
        'Jogo de copos',
        null,
        'Copos para agua, sucos e momentos especiais.',
        'https://www.mercadolivre.com.br/jogo-6-copos-de-vidro-canelado-cameratta-agua-suco-420ml/up/MLBU3216811619?pdp_filters=item_id%3AMLB4085176731&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB4085176731',
        'IMGS/produtos/10.jpeg',
        28,
        null,
        null,
        null
    ),
    (
        '11',
        'Essencial',
        'Xicaras',
        null,
        'Jogo para cafe e cha no dia a dia.',
        'https://www.mercadolivre.com.br/jogo-de-xicara-com-pires-6-pecas-brasiliano-vidro-cafe-cha/up/MLBU3563750460?pdp_filters=item_id%3AMLB5933197116&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB5933197116',
        'IMGS/produtos/11.jpeg',
        29,
        null,
        null,
        null
    ),
    (
        '17',
        'Essencial',
        'Escorredor de louca',
        null,
        'Ajuda a organizar pratos, copos e talheres apos a lavagem.',
        'https://www.mercadolivre.com.br/escorredor-de-louca-inox-20-pratos-2-andares-porta-talheres-prateado/p/MLB36202148?pdp_filters=item_id%3AMLB4100648425&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB4100648425',
        'IMGS/produtos/17.jpeg',
        30,
        null,
        null,
        null
    ),
    (
        '18',
        'Essencial',
        'Lixeira de cozinha',
        null,
        'Item pratico para manter a cozinha organizada.',
        'https://www.mercadolivre.com.br/dispenser-sabao-detergente-lixeira-e-rodinho-kit-cozinha/up/MLBU757567821?pdp_filters=item_id%3AMLB3280727197&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB3280727197',
        'IMGS/produtos/18.jpeg',
        31,
        null,
        null,
        null
    ),
    (
        '19',
        'Essencial',
        'Tabua de corte',
        null,
        'Essencial para apoiar o preparo das refeicoes.',
        'https://www.mercadolivre.com.br/tabua-de-vidro-temperado-pcarne-churrasco-higienica-fume/up/MLBU2173927220?pdp_filters=item_id%3AMLB2678350207&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB2678350207',
        'IMGS/produtos/19.png',
        32,
        null,
        null,
        null
    ),
    (
        '20',
        'Essencial',
        'Jogo de facas',
        null,
        'Conjunto para o preparo das refeicoes da casa.',
        'https://www.mercadolivre.com.br/jogo-de-facas-faqueiro-9-pecas-plenus-aco-inox-tramontina/p/MLB28408264?pdp_filters=item_id%3AMLB3782589243&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB3782589243',
        'IMGS/produtos/20.jpeg',
        33,
        null,
        null,
        null
    ),

    (
        '24',
        'Essencial',
        'Toalha de mesa',
        null,
        'Peca para compor e proteger a mesa das refeicoes.',
        'https://www.mercadolivre.com.br/toalha-de-mesa-jacquard-6-lugares-admirare-cor-silver/p/MLB28824623?pdp_filters=item_id%3AMLB4289065607&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB4289065607',
        'IMGS/produtos/24.jpeg',
        34,
        null,
        null,
        null
    ),
    (
        '26',
        'Essencial',
        'Panos de prato',
        null,
        'Essenciais para a rotina e organizacao da cozinha.',
        'https://www.mercadolivre.com.br/kit-10-pano-cozinha-louca-grande-xadrez-branco-alta-absorcao/up/MLBU3661991473?pdp_filters=item_id%3AMLB4355455435&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB4355455435',
        'IMGS/produtos/26.jpeg',
        35,
        null,
        null,
        null
    ),
    (
        '30',
        'Essencial',
        'Porta talheres organizador',
        null,
        'Organizador pratico para manter a gaveta em ordem.',
        'https://www.mercadolivre.com.br/porta-talheres-organizador-gaveta-com-extensor-8-divisorias/up/MLBU3675394059?pdp_filters=item_id%3AMLB6057087548&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB6057087548',
        'IMGS/produtos/30.jpeg',
        36,
        null,
        null,
        null
    ),
    (
        '33',
        'Essencial',
        'Kit saboneteira',
        null,
        'Kit para organizar e complementar o lavabo.',
        'https://produto.mercadolivre.com.br/MLB-4198550637-kit-lavabo-banheiro-bandeja-sabonete-liquido-escova-3-pecas-_JM?matt_tool=38524122#origin=whatsapp&sid=whatsapp',
        'IMGS/produtos/33.jpeg',
        37,
        null,
        null,
        null
    ),
    (
        '34',
        'Essencial',
        'Tapete de banheiro',
        null,
        'Conjunto para deixar o banheiro mais confortavel e seguro.',
        'https://www.mercadolivre.com.br/jogo-tapete-banheiro-2-pecas-antiderrapante-macio-absorvente/up/MLBU3936269858?pdp_filters=item_id%3AMLB6687742952&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB6687742952',
        'IMGS/produtos/34.jpeg',
        38,
        null,
        null,
        null
    ),
    (
        '35',
        'Essencial',
        'Lixeira de banheiro',
        null,
        'Item funcional para organizar o banheiro com praticidade.',
        'https://www.mercadolivre.com.br/kit-banheiro-luxo-lixeira-inox-3l-escova-com-suporte-cor-cinza/p/MLB48479950?pdp_filters=item_id%3AMLB4345379339&matt_tool=38524122#origin=whatsapp&sid=whatsapp&wid=MLB4345379339',
        'IMGS/produtos/35.jpeg',
        39,
        null,
        null,
        null
    );